### ISSUE TITLE
内容重复

### ISSUE THREAD

**Issue by defp** [forrestchang/Cuckoo#3]
示例 

http://dsh.li/blog/14996663897672.html

content 出现了两次，需要做什么设置吗？

**Comment by forrestchang** [comment]
需要填写 excerpt 字段用来作为正文的引言：

![](http://omaacpco9.bkt.clouddn.com/2017-07-12-151355.jpg)

或者你可以修改主题，把相关的 div 去掉。

**Comment by defp** [comment]
直接改模板了，没找到这个设置在哪

**Comment by forrestchang** [comment]
@lidashuang 你是用 Mweb 写的么，如果是的话，在旁边会有配置项的。

**Comment by defp** [comment]
是mweb，估计最近新版本改版了

**Comment by defp** [comment]
![image](https://user-images.githubusercontent.com/612381/28304409-0c2e0c54-6bca-11e7-93e8-043083092178.png)
搞了两个配置过来

**Comment by forrestchang** [comment]
@lidashuang 我看了一下，新版好像也可以配置的；你提一下 PR吧。
